// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: service.proto

package e2e

import (
	proto "github.com/golang/protobuf/proto"
	painters "github.com/tmc/protoc-gen-graphql/e2e/painters"
	_ "github.com/tmc/protoc-gen-graphql/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TrafficLight int32

const (
	TrafficLight_RED    TrafficLight = 0
	TrafficLight_YELLOW TrafficLight = 1
	TrafficLight_GREEN  TrafficLight = 2
)

// Enum value maps for TrafficLight.
var (
	TrafficLight_name = map[int32]string{
		0: "RED",
		1: "YELLOW",
		2: "GREEN",
	}
	TrafficLight_value = map[string]int32{
		"RED":    0,
		"YELLOW": 1,
		"GREEN":  2,
	}
)

func (x TrafficLight) Enum() *TrafficLight {
	p := new(TrafficLight)
	*p = x
	return p
}

func (x TrafficLight) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficLight) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (TrafficLight) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x TrafficLight) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficLight.Descriptor instead.
func (TrafficLight) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type HelloReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloReq) Reset() {
	*x = HelloReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloReq) ProtoMessage() {}

func (x *HelloReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloReq.ProtoReflect.Descriptor instead.
func (*HelloReq) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *HelloReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *HelloResp) Reset() {
	*x = HelloResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResp) ProtoMessage() {}

func (x *HelloResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResp.ProtoReflect.Descriptor instead.
func (*HelloResp) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResp) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TrafficJamReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Color         TrafficLight   `protobuf:"varint,1,opt,name=color,proto3,enum=e2e.TrafficLight" json:"color,omitempty"`
	TrafficLights []TrafficLight `protobuf:"varint,2,rep,packed,name=trafficLights,proto3,enum=e2e.TrafficLight" json:"trafficLights,omitempty"`
}

func (x *TrafficJamReq) Reset() {
	*x = TrafficJamReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrafficJamReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficJamReq) ProtoMessage() {}

func (x *TrafficJamReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficJamReq.ProtoReflect.Descriptor instead.
func (*TrafficJamReq) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *TrafficJamReq) GetColor() TrafficLight {
	if x != nil {
		return x.Color
	}
	return TrafficLight_RED
}

func (x *TrafficJamReq) GetTrafficLights() []TrafficLight {
	if x != nil {
		return x.TrafficLights
	}
	return nil
}

type TrafficJamResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Next TrafficLight `protobuf:"varint,1,opt,name=next,proto3,enum=e2e.TrafficLight" json:"next,omitempty"`
}

func (x *TrafficJamResp) Reset() {
	*x = TrafficJamResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrafficJamResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficJamResp) ProtoMessage() {}

func (x *TrafficJamResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficJamResp.ProtoReflect.Descriptor instead.
func (*TrafficJamResp) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *TrafficJamResp) GetNext() TrafficLight {
	if x != nil {
		return x.Next
	}
	return TrafficLight_RED
}

type PaintersReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PaintersReq) Reset() {
	*x = PaintersReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaintersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaintersReq) ProtoMessage() {}

func (x *PaintersReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaintersReq.ProtoReflect.Descriptor instead.
func (*PaintersReq) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

type PaintersResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BestPainter *painters.Painter `protobuf:"bytes,1,opt,name=bestPainter,proto3" json:"bestPainter,omitempty"`
	AllPainters []string          `protobuf:"bytes,2,rep,name=allPainters,proto3" json:"allPainters,omitempty"`
}

func (x *PaintersResp) Reset() {
	*x = PaintersResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PaintersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaintersResp) ProtoMessage() {}

func (x *PaintersResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaintersResp.ProtoReflect.Descriptor instead.
func (*PaintersResp) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *PaintersResp) GetBestPainter() *painters.Painter {
	if x != nil {
		return x.BestPainter
	}
	return nil
}

func (x *PaintersResp) GetAllPainters() []string {
	if x != nil {
		return x.AllPainters
	}
	return nil
}

type TranslateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Translations map[string]*Word `protobuf:"bytes,1,rep,name=translations,proto3" json:"translations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TranslateResp) Reset() {
	*x = TranslateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateResp) ProtoMessage() {}

func (x *TranslateResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateResp.ProtoReflect.Descriptor instead.
func (*TranslateResp) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *TranslateResp) GetTranslations() map[string]*Word {
	if x != nil {
		return x.Translations
	}
	return nil
}

type Word struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word     string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Language string `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
}

func (x *Word) Reset() {
	*x = Word{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *Word) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Word) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

type TranslateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words map[string]*Word `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TranslateReq) Reset() {
	*x = TranslateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateReq) ProtoMessage() {}

func (x *TranslateReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateReq.ProtoReflect.Descriptor instead.
func (*TranslateReq) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *TranslateReq) GetWords() map[string]*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

type BreadReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *BreadReq) Reset() {
	*x = BreadReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadReq) ProtoMessage() {}

func (x *BreadReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadReq.ProtoReflect.Descriptor instead.
func (*BreadReq) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *BreadReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BreadResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Answer:
	//	*BreadResp_Name
	//	*BreadResp_Toasted
	Answer isBreadResp_Answer `protobuf_oneof:"answer"`
}

func (x *BreadResp) Reset() {
	*x = BreadResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BreadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BreadResp) ProtoMessage() {}

func (x *BreadResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BreadResp.ProtoReflect.Descriptor instead.
func (*BreadResp) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (m *BreadResp) GetAnswer() isBreadResp_Answer {
	if m != nil {
		return m.Answer
	}
	return nil
}

func (x *BreadResp) GetName() string {
	if x, ok := x.GetAnswer().(*BreadResp_Name); ok {
		return x.Name
	}
	return ""
}

func (x *BreadResp) GetToasted() bool {
	if x, ok := x.GetAnswer().(*BreadResp_Toasted); ok {
		return x.Toasted
	}
	return false
}

type isBreadResp_Answer interface {
	isBreadResp_Answer()
}

type BreadResp_Name struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3,oneof"`
}

type BreadResp_Toasted struct {
	Toasted bool `protobuf:"varint,2,opt,name=toasted,proto3,oneof"`
}

func (*BreadResp_Name) isBreadResp_Answer() {}

func (*BreadResp_Toasted) isBreadResp_Answer() {}

type ChangeMeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Previous map[string]*ChangeMeResp `protobuf:"bytes,2,rep,name=previous,proto3" json:"previous,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ChangeMeReq) Reset() {
	*x = ChangeMeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeMeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMeReq) ProtoMessage() {}

func (x *ChangeMeReq) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMeReq.ProtoReflect.Descriptor instead.
func (*ChangeMeReq) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *ChangeMeReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChangeMeReq) GetPrevious() map[string]*ChangeMeResp {
	if x != nil {
		return x.Previous
	}
	return nil
}

type ChangeMeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are assignable to Answer:
	//	*ChangeMeResp_NewName
	//	*ChangeMeResp_Changed
	Answer   isChangeMeResp_Answer    `protobuf_oneof:"answer"`
	Previous map[string]*ChangeMeResp `protobuf:"bytes,4,rep,name=previous,proto3" json:"previous,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ChangeMeResp) Reset() {
	*x = ChangeMeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeMeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMeResp) ProtoMessage() {}

func (x *ChangeMeResp) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMeResp.ProtoReflect.Descriptor instead.
func (*ChangeMeResp) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *ChangeMeResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *ChangeMeResp) GetAnswer() isChangeMeResp_Answer {
	if m != nil {
		return m.Answer
	}
	return nil
}

func (x *ChangeMeResp) GetNewName() string {
	if x, ok := x.GetAnswer().(*ChangeMeResp_NewName); ok {
		return x.NewName
	}
	return ""
}

func (x *ChangeMeResp) GetChanged() bool {
	if x, ok := x.GetAnswer().(*ChangeMeResp_Changed); ok {
		return x.Changed
	}
	return false
}

func (x *ChangeMeResp) GetPrevious() map[string]*ChangeMeResp {
	if x != nil {
		return x.Previous
	}
	return nil
}

type isChangeMeResp_Answer interface {
	isChangeMeResp_Answer()
}

type ChangeMeResp_NewName struct {
	NewName string `protobuf:"bytes,2,opt,name=newName,proto3,oneof"`
}

type ChangeMeResp_Changed struct {
	Changed bool `protobuf:"varint,3,opt,name=changed,proto3,oneof"`
}

func (*ChangeMeResp_NewName) isChangeMeResp_Answer() {}

func (*ChangeMeResp_Changed) isChangeMeResp_Answer() {}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x65, 0x32, 0x65, 0x1a, 0x17, 0x70, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x70,
	0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0d, 0x6f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x08,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x1f, 0x0a, 0x09,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x71, 0x0a,
	0x0d, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x27,
	0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e,
	0x65, 0x32, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4c, 0x69, 0x67, 0x68, 0x74,
	0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x37, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x66, 0x66,
	0x69, 0x63, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x11,
	0x2e, 0x65, 0x32, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4c, 0x69, 0x67, 0x68,
	0x74, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x22, 0x37, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x25, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4c, 0x69,
	0x67, 0x68, 0x74, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x61, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x22, 0x65, 0x0a, 0x0c, 0x50, 0x61, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a, 0x0b, 0x62, 0x65, 0x73, 0x74,
	0x50, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x70, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x50, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x52, 0x0b, 0x62, 0x65, 0x73, 0x74, 0x50, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x61, 0x6c, 0x6c, 0x50, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x6c, 0x6c, 0x50, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x73, 0x22,
	0xa5, 0x01, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x48, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0c, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x4a, 0x0a, 0x11, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x36, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x22,
	0x87, 0x01, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x32, 0x0a, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x77,
	0x6f, 0x72, 0x64, 0x73, 0x1a, 0x43, 0x0a, 0x0a, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x20, 0x0a, 0x08, 0x42, 0x72, 0x65,
	0x61, 0x64, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x47, 0x0a, 0x09, 0x42,
	0x72, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x07, 0x74, 0x6f, 0x61, 0x73, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x07, 0x74, 0x6f, 0x61, 0x73, 0x74, 0x65, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x61, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x22, 0xad, 0x01, 0x0a, 0x0b, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x76,
	0x69, 0x6f, 0x75, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x65, 0x32, 0x65,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x50, 0x72, 0x65,
	0x76, 0x69, 0x6f, 0x75, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76,
	0x69, 0x6f, 0x75, 0x73, 0x1a, 0x4e, 0x0a, 0x0d, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x43, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x4d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0xf1, 0x01, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x6e, 0x65, 0x77,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x6e, 0x65,
	0x77, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x64, 0x12, 0x3b, 0x0a, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x4d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x1a, 0x4e,
	0x0a, 0x0d, 0x50, 0x72, 0x65, 0x76, 0x69, 0x6f, 0x75, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x08,
	0x0a, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x2a, 0x2e, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x66,
	0x66, 0x69, 0x63, 0x4c, 0x69, 0x67, 0x68, 0x74, 0x12, 0x07, 0x0a, 0x03, 0x52, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x59, 0x45, 0x4c, 0x4c, 0x4f, 0x57, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x47, 0x52, 0x45, 0x45, 0x4e, 0x10, 0x02, 0x32, 0xb0, 0x02, 0x0a, 0x07, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x0d, 0x2e,
	0x65, 0x32, 0x65, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x65,
	0x32, 0x65, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x35, 0x0a, 0x0a,
	0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d, 0x12, 0x12, 0x2e, 0x65, 0x32, 0x65,
	0x2e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x65, 0x32, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x4a, 0x61, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x61, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x73, 0x12, 0x10, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x50, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x50, 0x61, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x65, 0x12, 0x11, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x42,
	0x72, 0x65, 0x61, 0x64, 0x12, 0x0d, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x42, 0x72, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x36, 0x0a, 0x08, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x12,
	0x10, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65, 0x52, 0x65,
	0x71, 0x1a, 0x11, 0x2e, 0x65, 0x32, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x05, 0xf2, 0x42, 0x02, 0x08, 0x01, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x3b, 0x65, 0x32, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_service_proto_goTypes = []interface{}{
	(TrafficLight)(0),        // 0: e2e.TrafficLight
	(*HelloReq)(nil),         // 1: e2e.HelloReq
	(*HelloResp)(nil),        // 2: e2e.HelloResp
	(*TrafficJamReq)(nil),    // 3: e2e.TrafficJamReq
	(*TrafficJamResp)(nil),   // 4: e2e.TrafficJamResp
	(*PaintersReq)(nil),      // 5: e2e.PaintersReq
	(*PaintersResp)(nil),     // 6: e2e.PaintersResp
	(*TranslateResp)(nil),    // 7: e2e.TranslateResp
	(*Word)(nil),             // 8: e2e.Word
	(*TranslateReq)(nil),     // 9: e2e.TranslateReq
	(*BreadReq)(nil),         // 10: e2e.BreadReq
	(*BreadResp)(nil),        // 11: e2e.BreadResp
	(*ChangeMeReq)(nil),      // 12: e2e.ChangeMeReq
	(*ChangeMeResp)(nil),     // 13: e2e.ChangeMeResp
	nil,                      // 14: e2e.TranslateResp.TranslationsEntry
	nil,                      // 15: e2e.TranslateReq.WordsEntry
	nil,                      // 16: e2e.ChangeMeReq.PreviousEntry
	nil,                      // 17: e2e.ChangeMeResp.PreviousEntry
	(*painters.Painter)(nil), // 18: painters.Painter
}
var file_service_proto_depIdxs = []int32{
	0,  // 0: e2e.TrafficJamReq.color:type_name -> e2e.TrafficLight
	0,  // 1: e2e.TrafficJamReq.trafficLights:type_name -> e2e.TrafficLight
	0,  // 2: e2e.TrafficJamResp.next:type_name -> e2e.TrafficLight
	18, // 3: e2e.PaintersResp.bestPainter:type_name -> painters.Painter
	14, // 4: e2e.TranslateResp.translations:type_name -> e2e.TranslateResp.TranslationsEntry
	15, // 5: e2e.TranslateReq.words:type_name -> e2e.TranslateReq.WordsEntry
	16, // 6: e2e.ChangeMeReq.previous:type_name -> e2e.ChangeMeReq.PreviousEntry
	17, // 7: e2e.ChangeMeResp.previous:type_name -> e2e.ChangeMeResp.PreviousEntry
	8,  // 8: e2e.TranslateResp.TranslationsEntry.value:type_name -> e2e.Word
	8,  // 9: e2e.TranslateReq.WordsEntry.value:type_name -> e2e.Word
	13, // 10: e2e.ChangeMeReq.PreviousEntry.value:type_name -> e2e.ChangeMeResp
	13, // 11: e2e.ChangeMeResp.PreviousEntry.value:type_name -> e2e.ChangeMeResp
	1,  // 12: e2e.Service.Hello:input_type -> e2e.HelloReq
	3,  // 13: e2e.Service.TrafficJam:input_type -> e2e.TrafficJamReq
	5,  // 14: e2e.Service.GetPainters:input_type -> e2e.PaintersReq
	9,  // 15: e2e.Service.Translate:input_type -> e2e.TranslateReq
	10, // 16: e2e.Service.Bread:input_type -> e2e.BreadReq
	12, // 17: e2e.Service.ChangeMe:input_type -> e2e.ChangeMeReq
	2,  // 18: e2e.Service.Hello:output_type -> e2e.HelloResp
	4,  // 19: e2e.Service.TrafficJam:output_type -> e2e.TrafficJamResp
	6,  // 20: e2e.Service.GetPainters:output_type -> e2e.PaintersResp
	7,  // 21: e2e.Service.Translate:output_type -> e2e.TranslateResp
	11, // 22: e2e.Service.Bread:output_type -> e2e.BreadResp
	13, // 23: e2e.Service.ChangeMe:output_type -> e2e.ChangeMeResp
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrafficJamReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrafficJamResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaintersReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PaintersResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Word); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreadReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BreadResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeMeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeMeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*BreadResp_Name)(nil),
		(*BreadResp_Toasted)(nil),
	}
	file_service_proto_msgTypes[12].OneofWrappers = []interface{}{
		(*ChangeMeResp_NewName)(nil),
		(*ChangeMeResp_Changed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
